---
layout: post
title: Python Debugging Trick&#58; pdb.pm()
---

Python's debugger, [pdb](https://docs.python.org/3/library/pdb.html), is a great tool. This post is about one of my favorite uses of pdb, `pdb.pm()`. `pdb.pm()` launches `pdb` to debug the most recently raised exception. When you find yourself saying "Shit! That exception occurred four layers deep in code I wasn't editting and setting up the state to reproduce this is going to take 20 minutes" or "I wish I could just debug right from where the exception was raised", `pdb.pm()` is what you want. 

As a working example, consider the following implementation of mergesort. It has a logic bug, duplicates memory and suffers from array expansion, we will only focus on the logic bug. 

```Python
def mergesort(xs): 
    if len(xs) == 1: 
        return xs 
    else: 
        left = mergesort(xs[:len(xs)//2]) 
        right = mergesort(xs[len(xs)//2:]) 
        ys = [] 
        left_i, right_i = 0, 0 
        while left_i < len(left) or right_i < len(right): 
            if left[left_i] <= right[right_i]: 
                ys.append(left[left_i]) 
                left_i += 1 
            else: 
                ys.append(right[right_i]) 
                right_i += 1 
        return ys 
```

If you try to use this code, you will get the following error

```Python
In [2]: mergesort([6,5,4,3,2,1])                                                                                                                                                                                  
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-30-15081790cedb> in <module>
----> 1 mergesort([6,5,4,3,2,1])

<ipython-input-28-cb4e97206eb8> in mergesort(xs)
      3         return xs
      4     else:
----> 5         left = mergesort(xs[:len(xs)//2])
      6         right = mergesort(xs[len(xs)//2:])
      7         ys = []

<ipython-input-28-cb4e97206eb8> in mergesort(xs)
      4     else:
      5         left = mergesort(xs[:len(xs)//2])
----> 6         right = mergesort(xs[len(xs)//2:])
      7         ys = []
      8         left_i, right_i = 0, 0

<ipython-input-28-cb4e97206eb8> in mergesort(xs)
      8         left_i, right_i = 0, 0
      9         while left_i < len(left) or right_i < len(right):
---> 10             if left[left_i] <= right[right_i]:
     11                 ys.append(left[left_i])
     12                 left_i += 1

IndexError: list index out of range
```

It may be obvious to you what happened, but we can use `pdb.pm()` to poke at the state to see what is going on.

```Python
In [33]: import pdb; pdb.pm()                                                                                                                                                                                      
> <ipython-input-28-cb4e97206eb8>(10)mergesort()
-> if left[left_i] <= right[right_i]:
(Pdb) left_i, right_i
(0, 1)
(Pdb) left
[5]
(Pdb) right
[4]
```

Ok, now we know what happened. Both `left` and `right` had a single element but the code tried to index the non-existent second element in `right`.

If we needed to, we could step up the traceback to understand the state.

```Python
(Pdb) u
> <ipython-input-28-cb4e97206eb8>(6)mergesort()
-> right = mergesort(xs[len(xs)//2:])
(Pdb) left
[6]
(Pdb) xs
[6, 5, 4]
(Pdb) xs[len(xs)//2:]
[5, 4]
```

Debugging exceptions becomes a lot easier once you become comfortable with `pdb.pm()`.
